name: dio_logger_request
description: Library for logging DIO package requests. Prints the request information to the console.
version: 1.0.0
homepage: https://github.com/jhonathanqz/dio_logger_response
repository: https://github.com/jhonathanqz/dio_logger_response

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
